settings:
    prefix_logs: true
    color_logs: true
    color_scheme: auto
    default_debounce_delay: 500ms
rules:
    - name: backend
      prefix: go
      color: blue
      watch:
        - action: exclude
          patterns:
            - vendor/**
            - '**/*_test.go'
            - bin/**
            - dist/**
        - action: include
          patterns:
            - 'cmd/**/*.go'
            - 'services/**/*.go'
            - '**/*.go'
            - go.mod
            - go.sum
      commands:
        - echo 'Building Go application...'
        - make wasm
        - go run cmd/serve/*.go
    - name: TypeScript Frontend
      prefix: web
      color: cyan
      workdir: "./web"
      watch:
        - action: exclude
          patterns:
            - node_modules/**
            - dist/**
            - build/**
            - '**/.*'
            - '**/*.log'
        - action: include
          patterns:
            - '**/*.ts'
            - '**/*.tsx'
            - '**/*.js'
            - '**/*.jsx'
            - package.json
            - tsconfig.json
      commands:
        - "echo '⚡ Building frontend...'"
        - "npm run build"
