settings:
    prefix_logs: true
    color_logs: true
    color_scheme: auto
    default_debounce_delay: 500ms
rules:
    - name: Go Backend
      prefix: go
      color: blue
      watch:
        - action: exclude
          patterns:
            - vendor/**
            - '**/*_test.go'
            - '**/.*'
            - bin/**
            - dist/**
        - action: include
          patterns:
            - '**/*.go'
            - go.mod
            - go.sum
      commands:
        - echo 'Building Go application...'
        - go build -o bin/app .
        - echo 'Starting Go application...'
        - ./bin/app
    - name: TypeScript Frontend
      prefix: ts
      color: cyan
      watch:
        - action: exclude
          patterns:
            - node_modules/**
            - dist/**
            - build/**
            - '**/.*'
            - '**/*.log'
        - action: include
          patterns:
            - '**/*.ts'
            - '**/*.tsx'
            - '**/*.js'
            - '**/*.jsx'
            - package.json
            - tsconfig.json
      commands:
        - echo 'Installing dependencies...'
        - npm install
        - echo 'Building TypeScript project...'
        - npm run build
        - echo 'Starting development server...'
        - npm run dev
